version: '3'
services:
  parser:
    build: .
    command:
    ports:
    - "5000:3000"
    depends_on:
    - "redis"
  redis:
    image: "redis:alpine"
    volumes:
    - 'redis:/data'
    ports:
    - '6380:6379'

volumes:
  redis:
